NUMERO_DE_NOS_CAMADA_ENTRADA = 63
NUMERO_DE_CAMADAS_ESCONDIDAS = 2
NUMERO_DE_NOS_CAMADA_ESCONDIDA = 5
NUMERO_DE_NOS_CAMADA_SAIDA = 7

TAXA_DE_APRENDIZADO = 0.85
BIAS = 0.5
NUMERO_DE_EPOCAS = 3

ARQUIVO_DE_LEITURA = 'Part-1/caracteres-limpos.csv'
